[package]
name = "rust_advanced"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
futures = "0.3.31"
